Basic:

In [2]:
import numpy as np

a = [20, 30, 40]
b = [60, 70, 80]
a = np.array(a)
b = np.array(b)
print(a+b)
print(a*b)

[ 80 100 120]
[1200 2100 3200]


In [4]:
a = [[30,40,50],[40,30,10]]
arr = np.array(a)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 50]
 [40 30 10]]
2
(2, 3)
6
<class 'numpy.ndarray'>
int32
[[30. 40. 50.]
 [40. 30. 10.]]


In [6]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [8]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [10]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [12]:
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


Concatenation:

In [14]:
import numpy as np
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate((arr1,arr2)))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [16]:
print(np.vstack((arr1,arr2))) #vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


Adding and Removing:

In [18]:
import numpy as np

a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [20]:
print(np.insert(a,1,50))

[20 50 40 60 80]


In [22]:
print(np.insert(a,[1,2],[50],axis = 0)) #array,index,value

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


Search ,Sort and Filter:

In [24]:
ar = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [26]:
ar1 = np.array([7,8,4,12,9])
print(np.where(ar1 % 2 == 0))

(array([1, 2, 3], dtype=int64),)


In [28]:
a = np.array([20,30,40,50,60])
x = [True,False,True,False,True]
print(a[x])

[20 40 60]


Statistical Functions:

In [30]:
import statistics as stats
a = np.array([20,40,60,70])
b = np.array([100,300,700,100,500])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.cumsum(a))
print(np.cumprod(a))
print("\n")
print(np.mean(b))
print(np.median(b))
print(stats.mode(b))
print(np.std(b))
print(np.var(b))

20
70
190
47.5
50.0
[ 20  60 120 190]
[     20     800   48000 3360000]


340.0
300.0
100
233.23807579381202
54400.0


In [32]:
a = [100,150,199,200, 250, 130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
print()
print(np.cumprod([price,quantity],axis = 0))

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
